Added custom status in user profile popover
brightscout-alpha/mattermost-webapp pull request #7
Opened 2021-01-11 13:08 UTC by jatinjtg

2021-01-14 06:21 UTC, chetanyakan requested changes

2021-01-14 06:21 UTC, chetanyakan commented on components/custom_status/custom_status_emoji.tsx
> +        statusText = (
Should we create another component to show both emoji and text??

2021-01-14 06:21 UTC, chetanyakan commented on components/custom_status/custom_status_emoji.tsx
>      const customStatus = JSON.parse(currentUser.props.customStatus);
should we use the custom status selector??

2021-01-14 06:21 UTC, chetanyakan commented on components/profile_popover/profile_popover.jsx
> +                            marginRight: '4px',
```suggestion
                            marginRight: 4,
```

2021-01-14 06:21 UTC, chetanyakan commented on components/status_dropdown/index.jsx
> +        customStatus: getCustomStatus(state),
Should we change this selector to pass an ID?
This way, we can get the status for all users.

We can default to the current user's status.

2021-01-14 06:21 UTC, chetanyakan commented on components/status_dropdown/status_dropdown.jsx
> +        const isStatusSet = customStatus && (customStatus.text || customStatus.emoji);
We should verify if we allow empty status texts.

2021-01-14 06:21 UTC, chetanyakan commented on selectors/views/custom_status.ts
> +export function getCustomStatus(state: GlobalState) {
Same here, alow passing a `userID`.

2021-01-18 05:42 UTC, chetanyakan commented
1. UX Clarification
2. Slash command - investigation

2021-01-18 07:07 UTC, chetanyakan requested changes

2021-01-18 07:07 UTC, chetanyakan commented on components/channel_header/channel_header.js
> +                            margin: '0px 4px',
No need to specify dimensions for `0`

```suggestion
                            margin: '0 4px',
```

2021-01-18 07:07 UTC, chetanyakan commented on components/custom_status/custom_status_emoji.tsx
> +    if (!customStatusEnabled) {
nit - Merge these checks

```suggestion
    if (!customStatusEnabled || !customStatus || !customStatus.emoji) {
```

2021-01-18 07:07 UTC, chetanyakan commented on components/custom_status/custom_status_emoji.tsx
> +    });
If `isCustomStatusEnabled` is an arrow function, would this work?

```suggestion
    const customStatusEnabled = useSelector(isCustomStatusEnabled);
```

If so, make similar changes elsewhere.

2021-01-18 07:07 UTC, chetanyakan commented on components/custom_status/custom_status_emoji.tsx
> +                            {' '}
Check if we should use the `Nbsp` component instead.

```ts
import Nbsp from 'components/html_entities/nbsp';
```

2021-01-18 07:07 UTC, chetanyakan commented on components/custom_status/custom_status_modal.tsx
> +const EMOJI_PICKER_WIDTH_OFFSET = 308;
Should we move this with the rest of the constants?

2021-01-18 07:07 UTC, chetanyakan commented on components/custom_status/custom_status_modal.tsx
> +
Should we move this to `utils`?

2021-01-18 07:07 UTC, chetanyakan commented on components/post_view/post_header/index.ts
> +        userID: currentUser.id,
Rename to `currentUserID`

```suggestion
        currentUserID: currentUser.id,
```

2021-01-18 07:07 UTC, chetanyakan commented on components/post_view/post_header/post_header.tsx
> +    userID: string;
Same here. Rename prop

2021-01-18 07:07 UTC, chetanyakan commented on components/post_view/post_header/index.ts
> +    const customStatus = user ? getCustomStatus(state, user.id) : {};
Should this user be `ownProps.post.user_id`?
```suggestion
    const customStatus = getCustomStatus(state, ownProps.post.user_id) || {};
```

2021-01-18 07:07 UTC, chetanyakan commented on components/post_view/post_header/post_header.tsx
> +                        margin: '4px 0px 0px 4px',
nit - 
```suggestion
                        margin: '4px 0 0 4px',
```

Also, check if shorthand `0 4px` works

2021-01-18 07:07 UTC, chetanyakan commented on components/profile_popover/profile_popover.jsx
> +                        >
1. Check if we should use something other than the `<a>` tag.
2. Add appropriate `aria` properties

2021-01-18 07:50 UTC, jatinjtg commented on components/custom_status/custom_status_modal.tsx
> +const EMOJI_PICKER_WIDTH_OFFSET = 308;
Doesn't make sense to move this in global constants, as the constant is only related to this component and will not be reused.

2021-01-18 08:00 UTC, jatinjtg commented on components/custom_status/custom_status_emoji.tsx
> +    });
`isCustomStatusEnabled` is not an arrow function.

2021-01-18 08:16 UTC, jatinjtg commented on components/post_view/post_header/index.ts
> +    const customStatus = user ? getCustomStatus(state, user.id) : {};
`ownProps.post.user_id` is same as `user.id`.

2021-01-18 09:14 UTC, jatinjtg commented on components/custom_status/custom_status_emoji.tsx
> +                            {' '}
The return type of Nbsp is ReactNode and the return type of custom_status_emoji is JSx component. So it gives typescript error to use Nbsp in custom_status_emoji  component.

2021-01-19 10:26 UTC, chetanyakan approved these changes

2021-01-19 10:27 UTC, merged